### ISSUE TITLE
Cannot make callStatic

### ISSUE THREAD

**Issue by MarArMar** [Rubilmax/ethers-multicall-provider#47]
## Current Behavior

For contracts like https://docs.uniswap.org/contracts/v3/reference/periphery/lens/QuoterV2

You may want to only do a static call to not spend money on the quote

When I try to do IWETH.callStatic.symbol() inside , I get this error

TypeError: Cannot read properties of undefined (reading 'symbol')

## Expected Behavior

Would make the static Call

## Steps to Reproduce the Problem

  1. Prepare a IERC20 multicall contract
  1. Make a static call like IWETH.callStatic.symbol()

## Environment

- Version: 3
- Platform: Win
- Node.js Version: 16

**Comment by Rubilmax** [comment]
Hi, thanks for reporting. This issue seems to not be related to this package, as this package doesn't overwrite anything related to the contract object `IWETH`. Can you provide the exact code which leads to the error you describe pls?

Just confirmed locally that using this package, you should be able to access `callStatic` on contract objects.
